### ISSUE TITLE
diagrama de secuencia

### ISSUE THREAD

**Issue by WichinRighetti** [WichinRighetti/BajaBnB#11]
secuencia de 

- login 
- reservacion 
- busqueda

**Comment by jmgg2711** [comment]
![Diagrama de secuencia LOGIN](https://user-images.githubusercontent.com/87924378/215700702-03a4a39d-4a8d-4da7-a929-e9335cca39df.png)
[Diagrama de secuencia LOGIN.zip](https://github.com/WichinRighetti/BajaBnB/files/10544066/Diagrama.de.secuencia.LOGIN.zip)

Archivo ZIP incluye el archivo editable del diagrama de secuencia en DRAWIO. La imagen PNG es el mismo diagrama para uso en editor de textos como MS-WORD

**Comment by WichinRighetti** [comment]
Diagrama de secuencia de Reservacion



![Image](https://user-images.githubusercontent.com/104880921/218640809-970bd2c8-f595-4f6b-9c2a-6c46297a11a2.png)

**Comment by WichinRighetti** [comment]
busqueda



![Image](https://user-images.githubusercontent.com/104880921/218640913-73e992cf-bde7-4626-a7e0-c6dfc48e119a.png)
